Repository getyourguide/dependabutler, pull requests merged in 2025-06, with the labels that each got.

#78 Update go.yml
  .github/workflows/go.yml
Labels: x-small

#81 [TP-13604] Add cooldown option
  README.md
  dependabutler-sample.yml
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
Labels: risk:low, small

#82 version 0.8
  CHANGELOG.md
  internal/pkg/config/config_test.go
Labels: x-small, risk:low
